[metadata.heroku]
  root-package = "github.com/cryptix/ssb-pubmon"
  go-version = "go1.10.1"
  install = [ "github.com/cryptix/ssb-pubmon" ]

[[constraint]]
  name = "github.com/cryptix/go"
  version = "^1.2.0"

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "3.3.0"

[[constraint]]
  name = "github.com/go-kit/kit"
  version = "0.6.0"

[[constraint]]
  branch = "master"
  name = "github.com/jinzhu/configor"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/jteeuwen/go-bindata"

[[constraint]]
  branch = "master"
  name = "github.com/microcosm-cc/bluemonday"

[[constraint]]
  branch = "master"
  name = "github.com/qor/action_bar"

[[constraint]]
  branch = "master"
  name = "github.com/qor/activity"

[[constraint]]
  branch = "master"
  name = "github.com/qor/auth_themes"

[[constraint]]
  branch = "master"
  name = "github.com/qor/filebox"

[[constraint]]
  branch = "master"
  name = "github.com/qor/help"

[[constraint]]
  branch = "master"
  name = "github.com/qor/i18n"

[[constraint]]
  branch = "master"
  name = "github.com/qor/l10n"

[[constraint]]
  branch = "master"
  name = "github.com/qor/media"

[[constraint]]
  branch = "master"
  name = "github.com/qor/notification"

[[constraint]]
  branch = "master"
  name = "github.com/qor/qor"

[[constraint]]
  branch = "master"
  name = "github.com/qor/roles"

[[constraint]]
  branch = "master"
  name = "github.com/qor/sorting"

[[constraint]]
  branch = "master"
  name = "github.com/qor/transition"

[[constraint]]
  branch = "master"
  name = "github.com/qor/validations"

[[constraint]]
  branch = "master"
  name = "github.com/qor/wildcard_router"

[[constraint]]
  branch = "master"
  name = "github.com/qor/worker"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

# use forks
[[override]]
  name = "github.com/qor/admin"
  source = "github.com/cryptix/qor_admin"
  revision = "e73aa4543e56cafc7a46027d3353f69b64ca91f4"

[[override]]
  name = "github.com/qor/assetfs"
  source = "github.com/cryptix/qor_assetfs"
  revision = "0690e5426d85d229d6e9c919d9637120347058d8"

[[override]]
  name = "github.com/qor/auth"
  source = "github.com/cryptix/qor_auth"
  revision = "35f1d6dea9a2cc13b571e6f6c557437f55655a08"

[[override]]
  name = "github.com/qor/auth_themes"
  source = "github.com/cryptix/qor_auth_themes"
  revision = "45a77b9ec82d221cb11936397565ed00150d1c7a"

[[override]]
  name = "github.com/qor/mailer"
  source = "github.com/cryptix/qor_mailer"
  revision = "2d5b212956cc0e7c81aa0e4834bfffad8c4ab6ac"

[[override]]
  name = "github.com/qor/middlewares"
  source = "github.com/cryptix/qor_middlewares"
  revision = "18127115fc91fd180a122c3a8e6c85078b0624e6"

[[override]]
  name = "github.com/qor/redirect_back"
  source = "github.com/cryptix/qor_redirect_back"
  revision = "275539f5ccf24815c8ac88ec932c1f49fd3f8c83"

[[override]]
  name = "github.com/qor/render"
  source = "github.com/cryptix/qor_render"
  revision="e7333e0f2548d73d4773f912e6f2c793d28f38ce"

[[override]]
  name = "github.com/qor/session"
  source = "github.com/cryptix/qor_session"
  revision = "33f14a897a1f40d1ba043b67e49b4070948f10c0"

# old version tags
[[override]]
  branch = "master"
  name = "github.com/qor/serializable_meta"

[[override]]
  branch = "master"
  name = "github.com/qor/responder"

[[override]]
  branch = "master"
  name = "github.com/qor/cache"

[[override]]
  branch = "master"
  name = "github.com/qor/audited"

[[override]]
  branch = "master"
  name = "github.com/qor/publish"

[[constraint]]
  name = "cryptoscope.co/go/hexagen"
  version = "0.1.0"
